import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { ThemeContextProvider } from '@/lib/ThemeContext'
import ThemeProvider from '@/lib/ThemeProvider'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
        <ThemeProvider>
        <Navbar />
        <section className='dark:bg-gray-800 dark:text-white'>
        {children}
        <Footer />
        </section>
        </ThemeProvider>
        </ThemeContextProvider>
        </body>
    </html>
  )
}
